---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-39-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-39
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12039
      protocol: UDP
      targetPort: 12039
      name: port-12039
    - port: 13039
      protocol: TCP
      targetPort: 13039
      name: port-13039
    - port: 15039
      protocol: TCP
      targetPort: 15039
      name: metrics
    - port: 16039
      protocol: TCP
      targetPort: 16039
      name: port-16039
  selector:
    app: ssv-node-39
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-39
  name: ssv-node-39
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-39
  template:
    metadata:
      labels:
        app: ssv-node-39
    spec:
      containers:
        - name: ssv-node-39
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12039
              name: port-12039
              protocol: UDP
              hostPort: 12039
            - containerPort: 13039
              name: port-13039
              hostPort: 13039
            - containerPort: 15039
              name: port-15039
              hostPort: 15039
            - containerPort: 16039
              name: port-16039
              hostPort: 16039
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15039"
            - name: SSV_API_PORT
              value: "16039"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-39
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-39-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-39
          persistentVolumeClaim:
            claimName: ssv-node-39
        - name: ssv-node-39-cm
          configMap:
            name: ssv-node-39-cm
      hostNetwork: true
