---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-5-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-5
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12005
      protocol: UDP
      targetPort: 12005
      name: port-12005
    - port: 13005
      protocol: TCP
      targetPort: 13005
      name: port-13005
    - port: 15005
      protocol: TCP
      targetPort: 15005
      name: metrics
    - port: 16005
      protocol: TCP
      targetPort: 16005
      name: port-16005
  selector:
    app: ssv-node-5
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-5
  name: ssv-node-5
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-5
  template:
    metadata:
      labels:
        app: ssv-node-5
    spec:
      containers:
        - name: ssv-node-5
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12005
              name: port-12005
              protocol: UDP
              hostPort: 12005
            - containerPort: 13005
              name: port-13005
              hostPort: 13005
            - containerPort: 15005
              name: port-15005
              hostPort: 15005
            - containerPort: 16005
              name: port-16005
              hostPort: 16005
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15005"
            - name: SSV_API_PORT
              value: "16005"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-5
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-5-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-5
          persistentVolumeClaim:
            claimName: ssv-node-5
        - name: ssv-node-5-cm
          configMap:
            name: ssv-node-5-cm
      hostNetwork: true
