---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-61-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-61
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12061
      protocol: UDP
      targetPort: 12061
      name: port-12061
    - port: 13061
      protocol: TCP
      targetPort: 13061
      name: port-13061
    - port: 15061
      protocol: TCP
      targetPort: 15061
      name: metrics
    - port: 16061
      protocol: TCP
      targetPort: 16061
      name: port-16061
  selector:
    app: ssv-node-61
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-61
  name: ssv-node-61
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-61
  template:
    metadata:
      labels:
        app: ssv-node-61
    spec:
      containers:
        - name: ssv-node-61
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12061
              name: port-12061
              protocol: UDP
              hostPort: 12061
            - containerPort: 13061
              name: port-13061
              hostPort: 13061
            - containerPort: 15061
              name: port-15061
              hostPort: 15061
            - containerPort: 16061
              name: port-16061
              hostPort: 16061
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15061"
            - name: SSV_API_PORT
              value: "16061"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-61
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-61-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-61
          persistentVolumeClaim:
            claimName: ssv-node-61
        - name: ssv-node-61-cm
          configMap:
            name: ssv-node-61-cm
      hostNetwork: true
