---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-71-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-71
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12071
      protocol: UDP
      targetPort: 12071
      name: port-12071
    - port: 13071
      protocol: TCP
      targetPort: 13071
      name: port-13071
    - port: 15071
      protocol: TCP
      targetPort: 15071
      name: metrics
    - port: 16071
      protocol: TCP
      targetPort: 16071
      name: port-16071
  selector:
    app: ssv-node-71
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-71
  name: ssv-node-71
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-71
  template:
    metadata:
      labels:
        app: ssv-node-71
    spec:
      containers:
        - name: ssv-node-71
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12071
              name: port-12071
              protocol: UDP
              hostPort: 12071
            - containerPort: 13071
              name: port-13071
              hostPort: 13071
            - containerPort: 15071
              name: port-15071
              hostPort: 15071
            - containerPort: 16071
              name: port-16071
              hostPort: 16071
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15071"
            - name: SSV_API_PORT
              value: "16071"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-71
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-71-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-71
          persistentVolumeClaim:
            claimName: ssv-node-71
        - name: ssv-node-71-cm
          configMap:
            name: ssv-node-71-cm
      hostNetwork: true
