---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-19-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-19
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12019
      protocol: UDP
      targetPort: 12019
      name: port-12019
    - port: 13019
      protocol: TCP
      targetPort: 13019
      name: port-13019
    - port: 15019
      protocol: TCP
      targetPort: 15019
      name: metrics
    - port: 16019
      protocol: TCP
      targetPort: 16019
      name: port-16019
  selector:
    app: ssv-node-19
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-19
  name: ssv-node-19
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-19
  template:
    metadata:
      labels:
        app: ssv-node-19
    spec:
      containers:
        - name: ssv-node-19
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12019
              name: port-12019
              protocol: UDP
              hostPort: 12019
            - containerPort: 13019
              name: port-13019
              hostPort: 13019
            - containerPort: 15019
              name: port-15019
              hostPort: 15019
            - containerPort: 16019
              name: port-16019
              hostPort: 16019
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15019"
            - name: SSV_API_PORT
              value: "16019"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-19
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-19-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-19
          persistentVolumeClaim:
            claimName: ssv-node-19
        - name: ssv-node-19-cm
          configMap:
            name: ssv-node-19-cm
      hostNetwork: true
