---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-72-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-72
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12072
      protocol: UDP
      targetPort: 12072
      name: port-12072
    - port: 13072
      protocol: TCP
      targetPort: 13072
      name: port-13072
    - port: 15072
      protocol: TCP
      targetPort: 15072
      name: metrics
    - port: 16072
      protocol: TCP
      targetPort: 16072
      name: port-16072
  selector:
    app: ssv-node-72
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-72
  name: ssv-node-72
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-72
  template:
    metadata:
      labels:
        app: ssv-node-72
    spec:
      containers:
        - name: ssv-node-72
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12072
              name: port-12072
              protocol: UDP
              hostPort: 12072
            - containerPort: 13072
              name: port-13072
              hostPort: 13072
            - containerPort: 15072
              name: port-15072
              hostPort: 15072
            - containerPort: 16072
              name: port-16072
              hostPort: 16072
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15072"
            - name: SSV_API_PORT
              value: "16072"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-72
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-72-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-72
          persistentVolumeClaim:
            claimName: ssv-node-72
        - name: ssv-node-72-cm
          configMap:
            name: ssv-node-72-cm
      hostNetwork: true
