---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-59-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-59
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12059
      protocol: UDP
      targetPort: 12059
      name: port-12059
    - port: 13059
      protocol: TCP
      targetPort: 13059
      name: port-13059
    - port: 15059
      protocol: TCP
      targetPort: 15059
      name: metrics
    - port: 16059
      protocol: TCP
      targetPort: 16059
      name: port-16059
  selector:
    app: ssv-node-59
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-59
  name: ssv-node-59
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-59
  template:
    metadata:
      labels:
        app: ssv-node-59
    spec:
      containers:
        - name: ssv-node-59
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12059
              name: port-12059
              protocol: UDP
              hostPort: 12059
            - containerPort: 13059
              name: port-13059
              hostPort: 13059
            - containerPort: 15059
              name: port-15059
              hostPort: 15059
            - containerPort: 16059
              name: port-16059
              hostPort: 16059
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15059"
            - name: SSV_API_PORT
              value: "16059"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-59
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-59-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-59
          persistentVolumeClaim:
            claimName: ssv-node-59
        - name: ssv-node-59-cm
          configMap:
            name: ssv-node-59-cm
      hostNetwork: true
