---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-62-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-62
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12062
      protocol: UDP
      targetPort: 12062
      name: port-12062
    - port: 13062
      protocol: TCP
      targetPort: 13062
      name: port-13062
    - port: 15062
      protocol: TCP
      targetPort: 15062
      name: metrics
    - port: 16062
      protocol: TCP
      targetPort: 16062
      name: port-16062
  selector:
    app: ssv-node-62
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-62
  name: ssv-node-62
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-62
  template:
    metadata:
      labels:
        app: ssv-node-62
    spec:
      containers:
        - name: ssv-node-62
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12062
              name: port-12062
              protocol: UDP
              hostPort: 12062
            - containerPort: 13062
              name: port-13062
              hostPort: 13062
            - containerPort: 15062
              name: port-15062
              hostPort: 15062
            - containerPort: 16062
              name: port-16062
              hostPort: 16062
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15062"
            - name: SSV_API_PORT
              value: "16062"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-62
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-62-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-62
          persistentVolumeClaim:
            claimName: ssv-node-62
        - name: ssv-node-62-cm
          configMap:
            name: ssv-node-62-cm
      hostNetwork: true
