---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-50-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-50
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12050
      protocol: UDP
      targetPort: 12050
      name: port-12050
    - port: 13050
      protocol: TCP
      targetPort: 13050
      name: port-13050
    - port: 15050
      protocol: TCP
      targetPort: 15050
      name: metrics
    - port: 16050
      protocol: TCP
      targetPort: 16050
      name: port-16050
  selector:
    app: ssv-node-50
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-50
  name: ssv-node-50
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-50
  template:
    metadata:
      labels:
        app: ssv-node-50
    spec:
      containers:
        - name: ssv-node-50
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12050
              name: port-12050
              protocol: UDP
              hostPort: 12050
            - containerPort: 13050
              name: port-13050
              hostPort: 13050
            - containerPort: 15050
              name: port-15050
              hostPort: 15050
            - containerPort: 16050
              name: port-16050
              hostPort: 16050
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15050"
            - name: SSV_API_PORT
              value: "16050"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-50
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-50-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-50
          persistentVolumeClaim:
            claimName: ssv-node-50
        - name: ssv-node-50-cm
          configMap:
            name: ssv-node-50-cm
      hostNetwork: true
