---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-29-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-29
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12029
      protocol: UDP
      targetPort: 12029
      name: port-12029
    - port: 13029
      protocol: TCP
      targetPort: 13029
      name: port-13029
    - port: 15029
      protocol: TCP
      targetPort: 15029
      name: metrics
    - port: 16029
      protocol: TCP
      targetPort: 16029
      name: port-16029
  selector:
    app: ssv-node-29
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-29
  name: ssv-node-29
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-29
  template:
    metadata:
      labels:
        app: ssv-node-29
    spec:
      containers:
        - name: ssv-node-29
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12029
              name: port-12029
              protocol: UDP
              hostPort: 12029
            - containerPort: 13029
              name: port-13029
              hostPort: 13029
            - containerPort: 15029
              name: port-15029
              hostPort: 15029
            - containerPort: 16029
              name: port-16029
              hostPort: 16029
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15029"
            - name: SSV_API_PORT
              value: "16029"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-29
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-29-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-29
          persistentVolumeClaim:
            claimName: ssv-node-29
        - name: ssv-node-29-cm
          configMap:
            name: ssv-node-29-cm
      hostNetwork: true
