---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-18-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-18
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12018
      protocol: UDP
      targetPort: 12018
      name: port-12018
    - port: 13018
      protocol: TCP
      targetPort: 13018
      name: port-13018
    - port: 15018
      protocol: TCP
      targetPort: 15018
      name: metrics
    - port: 16018
      protocol: TCP
      targetPort: 16018
      name: port-16018
  selector:
    app: ssv-node-18
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-18
  name: ssv-node-18
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-18
  template:
    metadata:
      labels:
        app: ssv-node-18
    spec:
      containers:
        - name: ssv-node-18
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12018
              name: port-12018
              protocol: UDP
              hostPort: 12018
            - containerPort: 13018
              name: port-13018
              hostPort: 13018
            - containerPort: 15018
              name: port-15018
              hostPort: 15018
            - containerPort: 16018
              name: port-16018
              hostPort: 16018
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15018"
            - name: SSV_API_PORT
              value: "16018"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-18
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-18-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-18
          persistentVolumeClaim:
            claimName: ssv-node-18
        - name: ssv-node-18-cm
          configMap:
            name: ssv-node-18-cm
      hostNetwork: true
