---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-63-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-63
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12063
      protocol: UDP
      targetPort: 12063
      name: port-12063
    - port: 13063
      protocol: TCP
      targetPort: 13063
      name: port-13063
    - port: 15063
      protocol: TCP
      targetPort: 15063
      name: metrics
    - port: 16063
      protocol: TCP
      targetPort: 16063
      name: port-16063
  selector:
    app: ssv-node-63
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-63
  name: ssv-node-63
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-63
  template:
    metadata:
      labels:
        app: ssv-node-63
    spec:
      containers:
        - name: ssv-node-63
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12063
              name: port-12063
              protocol: UDP
              hostPort: 12063
            - containerPort: 13063
              name: port-13063
              hostPort: 13063
            - containerPort: 15063
              name: port-15063
              hostPort: 15063
            - containerPort: 16063
              name: port-16063
              hostPort: 16063
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15063"
            - name: SSV_API_PORT
              value: "16063"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-63
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-63-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-63
          persistentVolumeClaim:
            claimName: ssv-node-63
        - name: ssv-node-63-cm
          configMap:
            name: ssv-node-63-cm
      hostNetwork: true
