---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-10-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-10
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12010
      protocol: UDP
      targetPort: 12010
      name: port-12010
    - port: 13010
      protocol: TCP
      targetPort: 13010
      name: port-13010
    - port: 15010
      protocol: TCP
      targetPort: 15010
      name: metrics
    - port: 16010
      protocol: TCP
      targetPort: 16010
      name: port-16010
  selector:
    app: ssv-node-10
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-10
  name: ssv-node-10
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-10
  template:
    metadata:
      labels:
        app: ssv-node-10
    spec:
      containers:
        - name: ssv-node-10
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12010
              name: port-12010
              protocol: UDP
              hostPort: 12010
            - containerPort: 13010
              name: port-13010
              hostPort: 13010
            - containerPort: 15010
              name: port-15010
              hostPort: 15010
            - containerPort: 16010
              name: port-16010
              hostPort: 16010
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15010"
            - name: SSV_API_PORT
              value: "16010"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-10
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-10-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-10
          persistentVolumeClaim:
            claimName: ssv-node-10
        - name: ssv-node-10-cm
          configMap:
            name: ssv-node-10-cm
      hostNetwork: true
