---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-11-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-11
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12011
      protocol: UDP
      targetPort: 12011
      name: port-12011
    - port: 13011
      protocol: TCP
      targetPort: 13011
      name: port-13011
    - port: 15011
      protocol: TCP
      targetPort: 15011
      name: metrics
    - port: 16011
      protocol: TCP
      targetPort: 16011
      name: port-16011
  selector:
    app: ssv-node-11
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-11
  name: ssv-node-11
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-11
  template:
    metadata:
      labels:
        app: ssv-node-11
    spec:
      containers:
        - name: ssv-node-11
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12011
              name: port-12011
              protocol: UDP
              hostPort: 12011
            - containerPort: 13011
              name: port-13011
              hostPort: 13011
            - containerPort: 15011
              name: port-15011
              hostPort: 15011
            - containerPort: 16011
              name: port-16011
              hostPort: 16011
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15011"
            - name: SSV_API_PORT
              value: "16011"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-11
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-11-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-11
          persistentVolumeClaim:
            claimName: ssv-node-11
        - name: ssv-node-11-cm
          configMap:
            name: ssv-node-11-cm
      hostNetwork: true
