---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-26-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-26
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12026
      protocol: UDP
      targetPort: 12026
      name: port-12026
    - port: 13026
      protocol: TCP
      targetPort: 13026
      name: port-13026
    - port: 15026
      protocol: TCP
      targetPort: 15026
      name: metrics
    - port: 16026
      protocol: TCP
      targetPort: 16026
      name: port-16026
  selector:
    app: ssv-node-26
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-26
  name: ssv-node-26
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-26
  template:
    metadata:
      labels:
        app: ssv-node-26
    spec:
      containers:
        - name: ssv-node-26
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12026
              name: port-12026
              protocol: UDP
              hostPort: 12026
            - containerPort: 13026
              name: port-13026
              hostPort: 13026
            - containerPort: 15026
              name: port-15026
              hostPort: 15026
            - containerPort: 16026
              name: port-16026
              hostPort: 16026
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15026"
            - name: SSV_API_PORT
              value: "16026"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-26
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-26-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-26
          persistentVolumeClaim:
            claimName: ssv-node-26
        - name: ssv-node-26-cm
          configMap:
            name: ssv-node-26-cm
      hostNetwork: true
