---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-22-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-22
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12022
      protocol: UDP
      targetPort: 12022
      name: port-12022
    - port: 13022
      protocol: TCP
      targetPort: 13022
      name: port-13022
    - port: 15022
      protocol: TCP
      targetPort: 15022
      name: metrics
    - port: 16022
      protocol: TCP
      targetPort: 16022
      name: port-16022
  selector:
    app: ssv-node-22
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-22
  name: ssv-node-22
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-22
  template:
    metadata:
      labels:
        app: ssv-node-22
    spec:
      containers:
        - name: ssv-node-22
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12022
              name: port-12022
              protocol: UDP
              hostPort: 12022
            - containerPort: 13022
              name: port-13022
              hostPort: 13022
            - containerPort: 15022
              name: port-15022
              hostPort: 15022
            - containerPort: 16022
              name: port-16022
              hostPort: 16022
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15022"
            - name: SSV_API_PORT
              value: "16022"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-22
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-22-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-22
          persistentVolumeClaim:
            claimName: ssv-node-22
        - name: ssv-node-22-cm
          configMap:
            name: ssv-node-22-cm
      hostNetwork: true
