---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-8-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-8
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12008
      protocol: UDP
      targetPort: 12008
      name: port-12008
    - port: 13008
      protocol: TCP
      targetPort: 13008
      name: port-13008
    - port: 15008
      protocol: TCP
      targetPort: 15008
      name: metrics
    - port: 16008
      protocol: TCP
      targetPort: 16008
      name: port-16008
  selector:
    app: ssv-node-8
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-8
  name: ssv-node-8
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-8
  template:
    metadata:
      labels:
        app: ssv-node-8
    spec:
      containers:
        - name: ssv-node-8
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12008
              name: port-12008
              protocol: UDP
              hostPort: 12008
            - containerPort: 13008
              name: port-13008
              hostPort: 13008
            - containerPort: 15008
              name: port-15008
              hostPort: 15008
            - containerPort: 16008
              name: port-16008
              hostPort: 16008
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15008"
            - name: SSV_API_PORT
              value: "16008"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-8
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-8-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-8
          persistentVolumeClaim:
            claimName: ssv-node-8
        - name: ssv-node-8-cm
          configMap:
            name: ssv-node-8-cm
      hostNetwork: true
