---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-16-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-16
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12016
      protocol: UDP
      targetPort: 12016
      name: port-12016
    - port: 13016
      protocol: TCP
      targetPort: 13016
      name: port-13016
    - port: 15016
      protocol: TCP
      targetPort: 15016
      name: metrics
    - port: 16016
      protocol: TCP
      targetPort: 16016
      name: port-16016
  selector:
    app: ssv-node-16
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-16
  name: ssv-node-16
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-16
  template:
    metadata:
      labels:
        app: ssv-node-16
    spec:
      containers:
        - name: ssv-node-16
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12016
              name: port-12016
              protocol: UDP
              hostPort: 12016
            - containerPort: 13016
              name: port-13016
              hostPort: 13016
            - containerPort: 15016
              name: port-15016
              hostPort: 15016
            - containerPort: 16016
              name: port-16016
              hostPort: 16016
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15016"
            - name: SSV_API_PORT
              value: "16016"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-16
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-16-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-16
          persistentVolumeClaim:
            claimName: ssv-node-16
        - name: ssv-node-16-cm
          configMap:
            name: ssv-node-16-cm
      hostNetwork: true
