---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-13-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-13
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12013
      protocol: UDP
      targetPort: 12013
      name: port-12013
    - port: 13013
      protocol: TCP
      targetPort: 13013
      name: port-13013
    - port: 15013
      protocol: TCP
      targetPort: 15013
      name: metrics
    - port: 16013
      protocol: TCP
      targetPort: 16013
      name: port-16013
  selector:
    app: ssv-node-13
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-13
  name: ssv-node-13
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-13
  template:
    metadata:
      labels:
        app: ssv-node-13
    spec:
      containers:
        - name: ssv-node-13
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12013
              name: port-12013
              protocol: UDP
              hostPort: 12013
            - containerPort: 13013
              name: port-13013
              hostPort: 13013
            - containerPort: 15013
              name: port-15013
              hostPort: 15013
            - containerPort: 16013
              name: port-16013
              hostPort: 16013
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15013"
            - name: SSV_API_PORT
              value: "16013"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-13
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-13-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-13
          persistentVolumeClaim:
            claimName: ssv-node-13
        - name: ssv-node-13-cm
          configMap:
            name: ssv-node-13-cm
      hostNetwork: true
