---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-57-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-57
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12057
      protocol: UDP
      targetPort: 12057
      name: port-12057
    - port: 13057
      protocol: TCP
      targetPort: 13057
      name: port-13057
    - port: 15057
      protocol: TCP
      targetPort: 15057
      name: metrics
    - port: 16057
      protocol: TCP
      targetPort: 16057
      name: port-16057
  selector:
    app: ssv-node-57
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-57
  name: ssv-node-57
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-57
  template:
    metadata:
      labels:
        app: ssv-node-57
    spec:
      containers:
        - name: ssv-node-57
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12057
              name: port-12057
              protocol: UDP
              hostPort: 12057
            - containerPort: 13057
              name: port-13057
              hostPort: 13057
            - containerPort: 15057
              name: port-15057
              hostPort: 15057
            - containerPort: 16057
              name: port-16057
              hostPort: 16057
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15057"
            - name: SSV_API_PORT
              value: "16057"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-57
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-57-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-57
          persistentVolumeClaim:
            claimName: ssv-node-57
        - name: ssv-node-57-cm
          configMap:
            name: ssv-node-57-cm
      hostNetwork: true
