---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-46-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-46
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12046
      protocol: UDP
      targetPort: 12046
      name: port-12046
    - port: 13046
      protocol: TCP
      targetPort: 13046
      name: port-13046
    - port: 15046
      protocol: TCP
      targetPort: 15046
      name: metrics
    - port: 16046
      protocol: TCP
      targetPort: 16046
      name: port-16046
  selector:
    app: ssv-node-46
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-46
  name: ssv-node-46
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-46
  template:
    metadata:
      labels:
        app: ssv-node-46
    spec:
      containers:
        - name: ssv-node-46
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12046
              name: port-12046
              protocol: UDP
              hostPort: 12046
            - containerPort: 13046
              name: port-13046
              hostPort: 13046
            - containerPort: 15046
              name: port-15046
              hostPort: 15046
            - containerPort: 16046
              name: port-16046
              hostPort: 16046
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15046"
            - name: SSV_API_PORT
              value: "16046"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-46
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-46-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-46
          persistentVolumeClaim:
            claimName: ssv-node-46
        - name: ssv-node-46-cm
          configMap:
            name: ssv-node-46-cm
      hostNetwork: true
