---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-32-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-32
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12032
      protocol: UDP
      targetPort: 12032
      name: port-12032
    - port: 13032
      protocol: TCP
      targetPort: 13032
      name: port-13032
    - port: 15032
      protocol: TCP
      targetPort: 15032
      name: metrics
    - port: 16032
      protocol: TCP
      targetPort: 16032
      name: port-16032
  selector:
    app: ssv-node-32
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-32
  name: ssv-node-32
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-32
  template:
    metadata:
      labels:
        app: ssv-node-32
    spec:
      containers:
        - name: ssv-node-32
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12032
              name: port-12032
              protocol: UDP
              hostPort: 12032
            - containerPort: 13032
              name: port-13032
              hostPort: 13032
            - containerPort: 15032
              name: port-15032
              hostPort: 15032
            - containerPort: 16032
              name: port-16032
              hostPort: 16032
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15032"
            - name: SSV_API_PORT
              value: "16032"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-32
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-32-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-32
          persistentVolumeClaim:
            claimName: ssv-node-32
        - name: ssv-node-32-cm
          configMap:
            name: ssv-node-32-cm
      hostNetwork: true
