---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-42-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-42
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12042
      protocol: UDP
      targetPort: 12042
      name: port-12042
    - port: 13042
      protocol: TCP
      targetPort: 13042
      name: port-13042
    - port: 15042
      protocol: TCP
      targetPort: 15042
      name: metrics
    - port: 16042
      protocol: TCP
      targetPort: 16042
      name: port-16042
  selector:
    app: ssv-node-42
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-42
  name: ssv-node-42
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-42
  template:
    metadata:
      labels:
        app: ssv-node-42
    spec:
      containers:
        - name: ssv-node-42
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12042
              name: port-12042
              protocol: UDP
              hostPort: 12042
            - containerPort: 13042
              name: port-13042
              hostPort: 13042
            - containerPort: 15042
              name: port-15042
              hostPort: 15042
            - containerPort: 16042
              name: port-16042
              hostPort: 16042
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15042"
            - name: SSV_API_PORT
              value: "16042"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-42
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-42-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-42
          persistentVolumeClaim:
            claimName: ssv-node-42
        - name: ssv-node-42-cm
          configMap:
            name: ssv-node-42-cm
      hostNetwork: true
