---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-67-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-67
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12067
      protocol: UDP
      targetPort: 12067
      name: port-12067
    - port: 13067
      protocol: TCP
      targetPort: 13067
      name: port-13067
    - port: 15067
      protocol: TCP
      targetPort: 15067
      name: metrics
    - port: 16067
      protocol: TCP
      targetPort: 16067
      name: port-16067
  selector:
    app: ssv-node-67
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-67
  name: ssv-node-67
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-67
  template:
    metadata:
      labels:
        app: ssv-node-67
    spec:
      containers:
        - name: ssv-node-67
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12067
              name: port-12067
              protocol: UDP
              hostPort: 12067
            - containerPort: 13067
              name: port-13067
              hostPort: 13067
            - containerPort: 15067
              name: port-15067
              hostPort: 15067
            - containerPort: 16067
              name: port-16067
              hostPort: 16067
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15067"
            - name: SSV_API_PORT
              value: "16067"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-67
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-67-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-67
          persistentVolumeClaim:
            claimName: ssv-node-67
        - name: ssv-node-67-cm
          configMap:
            name: ssv-node-67-cm
      hostNetwork: true
