---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-3-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-3
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12003
      protocol: UDP
      targetPort: 12003
      name: port-12003
    - port: 13003
      protocol: TCP
      targetPort: 13003
      name: port-13003
    - port: 15003
      protocol: TCP
      targetPort: 15003
      name: metrics
    - port: 16003
      protocol: TCP
      targetPort: 16003
      name: port-16003
  selector:
    app: ssv-node-3
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-3
  name: ssv-node-3
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-3
  template:
    metadata:
      labels:
        app: ssv-node-3
    spec:
      containers:
        - name: ssv-node-3
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12003
              name: port-12003
              protocol: UDP
              hostPort: 12003
            - containerPort: 13003
              name: port-13003
              hostPort: 13003
            - containerPort: 15003
              name: port-15003
              hostPort: 15003
            - containerPort: 16003
              name: port-16003
              hostPort: 16003
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15003"
            - name: SSV_API_PORT
              value: "16003"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-3
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-3-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-3
          persistentVolumeClaim:
            claimName: ssv-node-3
        - name: ssv-node-3-cm
          configMap:
            name: ssv-node-3-cm
      hostNetwork: true
