---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-43-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-43
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12043
      protocol: UDP
      targetPort: 12043
      name: port-12043
    - port: 13043
      protocol: TCP
      targetPort: 13043
      name: port-13043
    - port: 15043
      protocol: TCP
      targetPort: 15043
      name: metrics
    - port: 16043
      protocol: TCP
      targetPort: 16043
      name: port-16043
  selector:
    app: ssv-node-43
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-43
  name: ssv-node-43
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-43
  template:
    metadata:
      labels:
        app: ssv-node-43
    spec:
      containers:
        - name: ssv-node-43
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12043
              name: port-12043
              protocol: UDP
              hostPort: 12043
            - containerPort: 13043
              name: port-13043
              hostPort: 13043
            - containerPort: 15043
              name: port-15043
              hostPort: 15043
            - containerPort: 16043
              name: port-16043
              hostPort: 16043
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15043"
            - name: SSV_API_PORT
              value: "16043"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-43
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-43-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-43
          persistentVolumeClaim:
            claimName: ssv-node-43
        - name: ssv-node-43-cm
          configMap:
            name: ssv-node-43-cm
      hostNetwork: true
