---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-36-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-36
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12036
      protocol: UDP
      targetPort: 12036
      name: port-12036
    - port: 13036
      protocol: TCP
      targetPort: 13036
      name: port-13036
    - port: 15036
      protocol: TCP
      targetPort: 15036
      name: metrics
    - port: 16036
      protocol: TCP
      targetPort: 16036
      name: port-16036
  selector:
    app: ssv-node-36
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-36
  name: ssv-node-36
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-36
  template:
    metadata:
      labels:
        app: ssv-node-36
    spec:
      containers:
        - name: ssv-node-36
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12036
              name: port-12036
              protocol: UDP
              hostPort: 12036
            - containerPort: 13036
              name: port-13036
              hostPort: 13036
            - containerPort: 15036
              name: port-15036
              hostPort: 15036
            - containerPort: 16036
              name: port-16036
              hostPort: 16036
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15036"
            - name: SSV_API_PORT
              value: "16036"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-36
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-36-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-36
          persistentVolumeClaim:
            claimName: ssv-node-36
        - name: ssv-node-36-cm
          configMap:
            name: ssv-node-36-cm
      hostNetwork: true
