---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-6-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-6
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12006
      protocol: UDP
      targetPort: 12006
      name: port-12006
    - port: 13006
      protocol: TCP
      targetPort: 13006
      name: port-13006
    - port: 15006
      protocol: TCP
      targetPort: 15006
      name: metrics
    - port: 16006
      protocol: TCP
      targetPort: 16006
      name: port-16006
  selector:
    app: ssv-node-6
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-6
  name: ssv-node-6
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-6
  template:
    metadata:
      labels:
        app: ssv-node-6
    spec:
      containers:
        - name: ssv-node-6
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12006
              name: port-12006
              protocol: UDP
              hostPort: 12006
            - containerPort: 13006
              name: port-13006
              hostPort: 13006
            - containerPort: 15006
              name: port-15006
              hostPort: 15006
            - containerPort: 16006
              name: port-16006
              hostPort: 16006
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15006"
            - name: SSV_API_PORT
              value: "16006"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-6
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-6-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-6
          persistentVolumeClaim:
            claimName: ssv-node-6
        - name: ssv-node-6-cm
          configMap:
            name: ssv-node-6-cm
      hostNetwork: true
