---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-23-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-23
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12023
      protocol: UDP
      targetPort: 12023
      name: port-12023
    - port: 13023
      protocol: TCP
      targetPort: 13023
      name: port-13023
    - port: 15023
      protocol: TCP
      targetPort: 15023
      name: metrics
    - port: 16023
      protocol: TCP
      targetPort: 16023
      name: port-16023
  selector:
    app: ssv-node-23
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-23
  name: ssv-node-23
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-23
  template:
    metadata:
      labels:
        app: ssv-node-23
    spec:
      containers:
        - name: ssv-node-23
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12023
              name: port-12023
              protocol: UDP
              hostPort: 12023
            - containerPort: 13023
              name: port-13023
              hostPort: 13023
            - containerPort: 15023
              name: port-15023
              hostPort: 15023
            - containerPort: 16023
              name: port-16023
              hostPort: 16023
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15023"
            - name: SSV_API_PORT
              value: "16023"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-23
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-23-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-23
          persistentVolumeClaim:
            claimName: ssv-node-23
        - name: ssv-node-23-cm
          configMap:
            name: ssv-node-23-cm
      hostNetwork: true
