---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-31-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-31
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12031
      protocol: UDP
      targetPort: 12031
      name: port-12031
    - port: 13031
      protocol: TCP
      targetPort: 13031
      name: port-13031
    - port: 15031
      protocol: TCP
      targetPort: 15031
      name: metrics
    - port: 16031
      protocol: TCP
      targetPort: 16031
      name: port-16031
  selector:
    app: ssv-node-31
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-31
  name: ssv-node-31
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-31
  template:
    metadata:
      labels:
        app: ssv-node-31
    spec:
      containers:
        - name: ssv-node-31
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12031
              name: port-12031
              protocol: UDP
              hostPort: 12031
            - containerPort: 13031
              name: port-13031
              hostPort: 13031
            - containerPort: 15031
              name: port-15031
              hostPort: 15031
            - containerPort: 16031
              name: port-16031
              hostPort: 16031
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15031"
            - name: SSV_API_PORT
              value: "16031"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-31
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-31-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-31
          persistentVolumeClaim:
            claimName: ssv-node-31
        - name: ssv-node-31-cm
          configMap:
            name: ssv-node-31-cm
      hostNetwork: true
