---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-51-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-51
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12051
      protocol: UDP
      targetPort: 12051
      name: port-12051
    - port: 13051
      protocol: TCP
      targetPort: 13051
      name: port-13051
    - port: 15051
      protocol: TCP
      targetPort: 15051
      name: metrics
    - port: 16051
      protocol: TCP
      targetPort: 16051
      name: port-16051
  selector:
    app: ssv-node-51
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-51
  name: ssv-node-51
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-51
  template:
    metadata:
      labels:
        app: ssv-node-51
    spec:
      containers:
        - name: ssv-node-51
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12051
              name: port-12051
              protocol: UDP
              hostPort: 12051
            - containerPort: 13051
              name: port-13051
              hostPort: 13051
            - containerPort: 15051
              name: port-15051
              hostPort: 15051
            - containerPort: 16051
              name: port-16051
              hostPort: 16051
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15051"
            - name: SSV_API_PORT
              value: "16051"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-51
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-51-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-51
          persistentVolumeClaim:
            claimName: ssv-node-51
        - name: ssv-node-51-cm
          configMap:
            name: ssv-node-51-cm
      hostNetwork: true
