---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-37-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-37
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12037
      protocol: UDP
      targetPort: 12037
      name: port-12037
    - port: 13037
      protocol: TCP
      targetPort: 13037
      name: port-13037
    - port: 15037
      protocol: TCP
      targetPort: 15037
      name: metrics
    - port: 16037
      protocol: TCP
      targetPort: 16037
      name: port-16037
  selector:
    app: ssv-node-37
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-37
  name: ssv-node-37
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-37
  template:
    metadata:
      labels:
        app: ssv-node-37
    spec:
      containers:
        - name: ssv-node-37
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12037
              name: port-12037
              protocol: UDP
              hostPort: 12037
            - containerPort: 13037
              name: port-13037
              hostPort: 13037
            - containerPort: 15037
              name: port-15037
              hostPort: 15037
            - containerPort: 16037
              name: port-16037
              hostPort: 16037
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15037"
            - name: SSV_API_PORT
              value: "16037"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-37
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-37-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-37
          persistentVolumeClaim:
            claimName: ssv-node-37
        - name: ssv-node-37-cm
          configMap:
            name: ssv-node-37-cm
      hostNetwork: true
