---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-20-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-20
    prometheus/app: ssv-node
spec:
  type: ClusterIP
  ports:
    - port: 12020
      protocol: UDP
      targetPort: 12020
      name: port-12020
    - port: 13020
      protocol: TCP
      targetPort: 13020
      name: port-13020
    - port: 15020
      protocol: TCP
      targetPort: 15020
      name: metrics
    - port: 16020
      protocol: TCP
      targetPort: 16020
      name: port-16020
  selector:
    app: ssv-node-20
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-20
  name: ssv-node-20
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-20
  template:
    metadata:
      labels:
        app: ssv-node-20
    spec:
      containers:
        - name: ssv-node-20
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          #image: mosheblox/ssv-preview:stage
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_NODES_CPU_LIMIT
              memory: REPLACE_NODES_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12020
              name: port-12020
              protocol: UDP
              hostPort: 12020
            - containerPort: 13020
              name: port-13020
              hostPort: 13020
            - containerPort: 15020
              name: port-15020
              hostPort: 15020
            - containerPort: 16020
              name: port-16020
              hostPort: 16020
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv/*."
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: CONSENSUS_TYPE
              value: "validation"
            - name: HOST_DNS
              value: ""
            - name: HOST_ADDRESS
              value: ""
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15020"
            - name: SSV_API_PORT
              value: "16020"
            - name: ENABLE_PROFILE
              value: "true"
            - name: DISCOVERY_TRACE
              value: 'false'
            - name: PUBSUB_TRACE
              value: 'false'
            - name: BUILDER_PROPOSALS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: ssv-node-20
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-node-20-cm
      imagePullSecrets:
        - name: ecr-repo
      volumes:
        - name: ssv-node-20
          persistentVolumeClaim:
            claimName: ssv-node-20
        - name: ssv-node-20-cm
          configMap:
            name: ssv-node-20-cm
      hostNetwork: true
